AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mom KID application

Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getMenuItems.handler
      Runtime: nodejs4.3
      Policies: AmazonDynamoDBReadOnlyAccess
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /menuitems
            Method: get

  AddMenIemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: addMenuItem.handler
      Runtime: nodejs4.3
      Policies: AmazonDynamoDBReadOnlyAccess
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /menuitems
            Method: post
            
  OrdersGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getOrders.handler
      Runtime: nodejs4.3
      Policies: AmazonDynamoDBReadOnlyAccess
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /orders
            Method: get

  Table:
    Type: AWS::Serverless::SimpleTable