AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple CRUD web service. State is stored in a DynamoDB table.
Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getMenuItems.handler
      Runtime: nodejs4.3
      Policies: AmazonDynamoDBReadOnlyAccess
      Timeout: 19
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /menuitems
            Method: get
  Table:
    Type: AWS::Serverless::SimpleTable

Outputs:
  ApiUrl:
    Description: URL for application
    Value: 'https://momkid.execute-api.us-west-2.amazonaws.com/staging'
    Export:
      Name: 'staging'