AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mom KID application

Resources:
  GetMenuItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getMenuItems.handler
      Runtime: nodejs4.3
      Policies: AmazonDynamoDBReadOnlyAccess
      CodeUri: src
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref MenuItemTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /menuitems
            Method: get

  AddMenIemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: addMenuItem.handler
      Runtime: nodejs4.3
      Policies: AmazonDynamoDBFullAccess
      CodeUri: src
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref MenuItemTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /menuitems
            Method: post
            
  RemoveMenIemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: removeMenuItem.handler
      Runtime: nodejs4.3
      Policies: AmazonDynamoDBFullAccess
      CodeUri: src
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref MenuItemTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /menuitems
            Method: delete

  GetOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getOrders.handler
      Runtime: nodejs4.3
      Policies: AmazonDynamoDBReadOnlyAccess
      CodeUri: src
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref OrderTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /orders
            Method: get

  AddOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: addOrders.handler
      Runtime: nodejs4.3
      Policies: AmazonDynamoDBFullAccess
      CodeUri: src
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref OrderTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /orders
            Method: post
            
  MenuItemTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
         Name: name
         Type: String
      ProvisionedThroughput:
         ReadCapacityUnits: 5
         WriteCapacityUnits: 5
  OrderTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
         Name: confirmationId
         Type: String
      ProvisionedThroughput:
         ReadCapacityUnits: 5
         WriteCapacityUnits: 5