version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file app_spec.yaml --s3-bucket momkid --output-template-file new_app_spec.yaml
artifacts:
  type: zip
  files:
    - new_app_spec.yaml
    - package.json
    - test/*
  
  discard-paths: no
  