AWSTemplateFormatVersion: '2010-09-09'
Description: Mom KID application
Resources:
  AddMenIemFunction:
    Properties:
      CodeUri: s3://momkid/4f17897d7840108f8ccefbe51c440af7
      Environment:
        Variables:
          TABLE_NAME:
            Ref: MenuItemTable
      Events:
        GetResource:
          Properties:
            Method: post
            Path: /menuitems
          Type: Api
      Handler: addMenuItem.handler
      Policies: AmazonDynamoDBReadOnlyAccess
      Runtime: nodejs4.3
      Timeout: 10
    Type: AWS::Serverless::Function
  AddOrderFunction:
    Properties:
      CodeUri: s3://momkid/4f17897d7840108f8ccefbe51c440af7
      Environment:
        Variables:
          TABLE_NAME:
            Ref: OrderTable
      Events:
        GetResource:
          Properties:
            Method: post
            Path: /orders
          Type: Api
      Handler: addOrders.handler
      Policies: AmazonDynamoDBReadOnlyAccess
      Runtime: nodejs4.3
      Timeout: 10
    Type: AWS::Serverless::Function
  GetMenuItemsFunction:
    Properties:
      CodeUri: s3://momkid/4f17897d7840108f8ccefbe51c440af7
      Environment:
        Variables:
          TABLE_NAME:
            Ref: MenuItemTable
      Events:
        GetResource:
          Properties:
            Method: get
            Path: /menuitems
          Type: Api
      Handler: getMenuItems.handler
      Policies: AmazonDynamoDBReadOnlyAccess
      Runtime: nodejs4.3
      Timeout: 10
    Type: AWS::Serverless::Function
  GetOrdersFunction:
    Properties:
      CodeUri: s3://momkid/4f17897d7840108f8ccefbe51c440af7
      Environment:
        Variables:
          TABLE_NAME:
            Ref: OrderTable
      Events:
        GetResource:
          Properties:
            Method: get
            Path: /orders
          Type: Api
      Handler: getOrders.handler
      Policies: AmazonDynamoDBReadOnlyAccess
      Runtime: nodejs4.3
      Timeout: 10
    Type: AWS::Serverless::Function
  MenuItemTable:
    Properties:
      PrimaryKey:
        Name: name
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Type: AWS::Serverless::SimpleTable
  OrderTable:
    Properties:
      PrimaryKey:
        Name: confirmation
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Type: AWS::Serverless::SimpleTable
  RemoveMenIemFunction:
    Properties:
      CodeUri: s3://momkid/4f17897d7840108f8ccefbe51c440af7
      Environment:
        Variables:
          TABLE_NAME:
            Ref: MenuItemTable
      Events:
        GetResource:
          Properties:
            Method: delete
            Path: /menuitems
          Type: Api
      Handler: removeMenuItem.handler
      Policies: AmazonDynamoDBReadOnlyAccess
      Runtime: nodejs4.3
      Timeout: 10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
